version: "3.8"

services:
  postgresqldb:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db

  minio:
    image: quay.io/minio/minio
    restart: on-failure
    command:
      server /data
    environment:
      - MINIO_ACCESS_KEY=username
      - MINIO_SECRET_KEY=password

  redis:
    image: redis
    restart: on-failure

  cloud-file-storage:
    image: icekubit/cloud-file-storage:v1.0.3
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgresqldb
      - MINIO_HOST=minio
      - REDIS_HOST=redis