version: "3.8"

services:
  postgresqldb:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_db
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    restart: on-failure
    ports:
      - "9000:9000"
      - "9001:9001"
    command:
      server /data
    environment:
      - MINIO_CONSOLE_ADDRESS=:9001
      - MINIO_ACCESS_KEY=username
      - MINIO_SECRET_KEY=password

  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"

  cloud-file-storage:
    image: icekubit/cloud-file-storage:v1.0.1
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgresqldb
      - MINIO_HOST=minio
      - REDIS_HOST=redis