version: "3.8"

services:
  myapp:
    build: .
    environment:
      MYSQL_HOST: mysqldb
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db