CREATE TABLE IF NOT EXISTS users
(
    id       int generated by default as identity
    primary key,
    email    varchar(255) unique not null,
    name     varchar(255) unique not null,
    password varchar(255) not null
);