--liquibase formatted sql

--changeset icekubit:1
CREATE TABLE IF NOT EXISTS users
(
    id       int generated by default as identity
        primary key,
    email    varchar(255) not null,
    name     varchar(255) not null,
    password varchar(255) not null
);

-- the title of this constraint should correspond to the string nameConstraint
-- in the icekubit.cloudfilestorage.auth.service.RegistrationService
ALTER TABLE users
    ADD CONSTRAINT unique_name UNIQUE (name);

-- the title of this constraint should correspond to the string emailConstraint
-- in the icekubit.cloudfilestorage.auth.service.RegistrationService
ALTER TABLE users
    ADD CONSTRAINT unique_email UNIQUE (email);